### ISSUE TITLE
Suggestion: `\textbf` to use `style='font-weight:bold;'` rather than convert to mathematical bold unicode range

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#10]
Some authors wish their `<mtext>` font and style to match the body of their document.

<details>

<summary>For example, I currently have a stylesheet like this (click to expand).</summary>

```css
:root {
  --main-font: 'SF Pro Display', system-ui, -apple-system, system, '.SFNSText-Regular', 'San Francisco', roboto, 'Segoe UI', 'Helvetica Neue', 'Lucida Grande', sans-serif;
},

body,
mtext {
  font-family: var(--main-font);
}
```

</details>

However, when I use `\textbf`, the result [does not match](https://temml.org/#%5Ctextbf%7BRate%20of%20change%20of%20sector%20area%7D%20=%20%5Cfrac%7B1%7D%7B2%7Dr%5E2%20%5Cdot%7B%CE%B8%7D) my expectations.

<details><summary>The current Temml functionality (click to see) is that both \mathbf and \textbf changes the Unicode characters to the mathematical bold range (and with \mathbf wrapping each character in an mi element ) </summary>

```html
<math display="block">
  <mrow>
    <mtext>𝐑𝐚𝐭𝐞 𝐨𝐟 𝐜𝐡𝐚𝐧𝐠𝐞 𝐨𝐟 𝐬𝐞𝐜𝐭𝐨𝐫 𝐚𝐫𝐞𝐚</mtext>
    <mo>=</mo>
    <mfrac>
      <mn>1</mn>
      <mn>2</mn>
    </mfrac>
    <msup>
      <mi>r</mi>
      <mn>2</mn>
    </msup>
    <mover>
      <mi>θ</mi>
      <mo stretchy="false" style="math-style:normal;math-depth:0;">˙</mo>
    </mover>
  </mrow>
</math>
```

</details>

My suggestion - please tell me if I'm misguided - is for Temml to set `style='font-weight:bold;'` as an attribute on each `<mtext>` generated by \textbf.  (Or maybe a class as part of the stylesheet?)

I suggest the current functionality remains for \mathbf.

So, the above HTML will be:

```html

<math display="block">
  <mrow>
    <mtext style='font-weight:bold;'>Rate of change of sector area</mtext>
    <mo>=</mo>
    <mfrac>
      <mn>1</mn>
      <mn>2</mn>
    </mfrac>
    <msup>
      <mi>r</mi>
      <mn>2</mn>
    </msup>
    <mover>
      <mi>θ</mi>
      <mo stretchy="false" style="math-style:normal;math-depth:0;">˙</mo>
    </mover>
  </mrow>
</math>
```

I'm vaguely aware of the discussions over css [math-variant-bold](https://wpt.fyi/results/mathml/relations/css-styling/mathvariant-bold.html?label=experimental&label=master&aligned) and similar, but I think that discussion is not directly relevant to my concern here?

Thoughts?
